# Generated by Django 5.1 on 2024-08-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_user_url_blog_created_blog_updated_blog_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog_images/'),
        ),
    ]
