# Generated by Django 5.1 on 2024-08-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_blog_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='profile_picture',
            field=models.ImageField(default='avatar.png', upload_to='blog_images/'),
        ),
    ]
